---
abstract: 'Web::XDO -- static web site tool'
author:
    - "Miko O'Sullivan <miko@idocs.com>"
generated_by: home grown
license: perl
name: Web::XDO
provides:
    Web::XDO:
        file: lib/Web/XDO.pm
        version: 0.11
requires:
    HTML::Parser: 0
    String::Util: 0
    URI::URL: 0
    perl: 5.003
version: 0.11
